#!/bin/sh
cd ${0%/*} || exit 1                            # Run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments # (for error catching)
. $WM_PROJECT_DIR/wmake/scripts/sysFunctions    # General system functions

#------------------------------------------------------------------------------

# Build libcork.a
cd cork
make

# Build alphaInitializerFoam
cd ..
wmake

#------------------------------------------------------------------------------
